# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20170118_2319'),
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_player',
        ),
        migrations.AddField(
            model_name='match',
            name='away_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_player', to='administration.Player'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_player',
        ),
        migrations.AddField(
            model_name='match',
            name='home_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_player', to='administration.Player'),
        ),
    ]
