# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='create_date',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='create_date',
            new_name='match_date',
        ),
        migrations.AddField(
            model_name='leg',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MatchWeek'),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MatchWeek'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Season'),
        ),
        migrations.AlterField(
            model_name='match',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Season'),
        ),
    ]
