# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='leg_id',
            field=models.IntegerField(default=0),
        ),
    ]
