# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_auto_20170207_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguematch',
            name='season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AddField(
            model_name='leaguematch',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
