# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('recording', '0002_auto_20170205_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.MatchWeek')),
            ],
        ),
    ]
