# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_leg_leg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='nb_frames',
            new_name='number_frames',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='nb_frames',
            new_name='number_frames',
        ),
        migrations.AlterField(
            model_name='leg',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='leg_id',
            field=models.IntegerField(default=0, verbose_name='Leg ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event date'),
        ),
    ]
