# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0005_auto_20170129_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to='administration.Member'),
        ),
    ]
