# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0006_auto_20170129_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='frame_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leagueframe',
            name='frame_number',
            field=models.IntegerField(default=0),
        ),
    ]
