# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0006_auto_20170305_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
