# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0007_auto_20170129_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='race_to',
            field=models.IntegerField(default=7),
        ),
    ]
