# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0008_auto_20170130_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='is_updated',
            new_name='is_submitted',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='is_updated',
            new_name='is_submitted',
        ),
    ]
