# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0009_auto_20170319_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguematch',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaguematch_away', to='administration.Team'),
        ),
        migrations.AlterField(
            model_name='leaguematch',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaguematch_home', to='administration.Team'),
        ),
    ]
