# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0009_auto_20170130_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg',
            old_name='leg_id',
            new_name='leg_number',
        ),
        migrations.AlterField(
            model_name='leg',
            name='score_type',
            field=models.CharField(choices=[('P', 'Points'), ('F', 'Frames')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_type',
            field=models.CharField(choices=[('P', 'Points'), ('F', 'Frames')], default='F', max_length=1),
        ),
    ]
