# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0010_auto_20170326_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguematch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaguematch_winner', to='administration.Team'),
        ),
    ]
