# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20170521_0052'),
        ('recording', '0012_auto_20170326_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguematch',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.League'),
        ),
    ]
