# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0013_leaguematch_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguematch',
            options={'permissions': (('view_leaguematch', 'Can view leaguematch'), ('record_leaguematch', 'Can record leaguematch'), ('approve_leaguematch', 'Can approve leaguematch'))},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'permissions': (('view_match', 'Can view match'), ('record_match', 'Can record match'), ('approve_match', 'Can approve match'))},
        ),
    ]
