# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 06:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ranking', models.IntegerField(default=0)),
                ('total_legs_played', models.IntegerField(default=0)),
                ('total_legs_won', models.IntegerField(default=0)),
                ('season_legs_played', models.IntegerField(default=0)),
                ('season_legs_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cancel_date', models.DateTimeField(blank=True, null=True, verbose_name='date quitted')),
                ('points', models.FloatField(default=1000.0)),
                ('ranking', models.IntegerField(default=0)),
                ('total_matches_played', models.IntegerField(default=0)),
                ('total_matches_won', models.IntegerField(default=0)),
                ('season_matches_played', models.IntegerField(default=0)),
                ('season_matches_won', models.IntegerField(default=0)),
                ('no_groups', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{8,15}$')])),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Group')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.League')),
            ],
            bases=('administration.group',),
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Group'),
        ),
        migrations.AddField(
            model_name='member',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Player'),
        ),
    ]
