# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex')], max_length=1)),
                ('joining_date', models.DateTimeField(verbose_name='date joined')),
                ('ranking_pts', models.FloatField(default=1000.0)),
                ('ranking', models.IntegerField(default=0)),
                ('total_matches_played', models.IntegerField(default=0)),
                ('total_matches_won', models.IntegerField(default=0)),
                ('season_matches_played', models.IntegerField(default=0)),
                ('season_matches_won', models.IntegerField(default=0)),
                ('no_groups', models.IntegerField(default=0)),
            ],
        ),
    ]
