# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date quitted'),
        ),
        migrations.AlterField(
            model_name='member',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
    ]
