# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='raw_points',
            field=models.IntegerField(default=0),
        ),
    ]
