# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('joining_date', models.DateTimeField(verbose_name='date joined')),
                ('ranking', models.IntegerField(default=0)),
                ('total_legs_played', models.IntegerField(default=0)),
                ('total_legs_won', models.IntegerField(default=0)),
                ('season_legs_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='player',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 15, 0, 54, 738369, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Team'),
        ),
    ]
