# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170118_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='team',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 15, 6, 0, 422965, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='team',
            name='season_legs_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 15, 6, 0, 431393, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
