# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20170118_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 15, 19, 57, 549852, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='team',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 18, 15, 19, 57, 522469, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
