# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20170118_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='team',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date joined'),
        ),
    ]
