# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_member__handicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date ended'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(default=0),
        ),
    ]
