# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20170129_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='group',
            name='season_legs_played',
        ),
        migrations.RemoveField(
            model_name='group',
            name='season_legs_won',
        ),
        migrations.RemoveField(
            model_name='group',
            name='total_legs_played',
        ),
        migrations.RemoveField(
            model_name='group',
            name='total_legs_won',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nb_groups',
        ),
        migrations.AddField(
            model_name='league',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='season_clearance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='total_clearance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nb_groups',
            field=models.IntegerField(default=0, verbose_name='Number of groups'),
        ),
        migrations.AddField(
            model_name='team',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_legs_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_legs_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_legs_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_legs_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='_match_adj',
            field=models.IntegerField(default=0, verbose_name='Matches to be added'),
        ),
        migrations.AlterField(
            model_name='member',
            name='_match_won_adj',
            field=models.IntegerField(default=0, verbose_name='Matches won to be added'),
        ),
        migrations.AlterField(
            model_name='member',
            name='_point_adj',
            field=models.FloatField(default=0.0, verbose_name='Points to be added'),
        ),
    ]
