# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20170129_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='_match_adj',
        ),
        migrations.RemoveField(
            model_name='member',
            name='_match_won_adj',
        ),
    ]
