# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20170119_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
