# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20170222_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='_handicap',
            new_name='handicap',
        ),
        migrations.AlterField(
            model_name='team',
            name='total_legs_played',
            field=models.IntegerField(default=-1),
        ),
    ]
