# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20170313_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='handicap',
            field=models.FloatField(default=-1),
        ),
    ]
