# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_league_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_legs_played',
            field=models.IntegerField(default=0),
        ),
    ]
