# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20170319_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
