# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20170625_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season_points',
            field=models.IntegerField(default=0),
        ),
    ]
