# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20170627_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='capitain',
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Member'),
        ),
    ]
