# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_auto_20170704_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonal',
            name='leg_average',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonal',
            name='median',
            field=models.IntegerField(default=0),
        ),
    ]
