# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_auto_20170823_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasonal',
            name='median',
            field=models.FloatField(default=0),
        ),
    ]
