# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_auto_20170823_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season_leg_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_median',
            field=models.FloatField(default=0),
        ),
    ]
