# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20170823_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='raw_points',
            new_name='season_points',
        ),
    ]
