# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_member_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_clearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
