# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_team_season_points'),
        ('schedule', '0003_auto_20170209_2050'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Current ranking date')),
                ('serial_id', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('elo_points', models.FloatField(blank=True, null=True)),
                ('raw_points', models.IntegerField(blank=True, null=True)),
                ('handicap', models.FloatField(blank=True, null=True)),
                ('clearances', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('legs_played', models.IntegerField(default=0)),
                ('legs_won', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.League')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Team')),
                ('weak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.MatchWeek')),
            ],
        ),
        migrations.RenameField(
            model_name='playerranking',
            old_name='season_clearance',
            new_name='clearance',
        ),
        migrations.RenameField(
            model_name='playerranking',
            old_name='season_matches_played',
            new_name='matches_played',
        ),
        migrations.RenameField(
            model_name='playerranking',
            old_name='season_matches_won',
            new_name='matches_won',
        ),
        migrations.RemoveField(
            model_name='playerranking',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playerranking',
            name='total_clearance',
        ),
        migrations.RemoveField(
            model_name='playerranking',
            name='total_matches_played',
        ),
        migrations.RemoveField(
            model_name='playerranking',
            name='total_matches_won',
        ),
        migrations.AddField(
            model_name='playerranking',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.League'),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MatchWeek'),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Member'),
        ),
    ]
