# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170626_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerranking',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.League'),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Member'),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.MatchWeek'),
        ),
    ]
