# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170627_2033'),
        ('stats', '0003_auto_20170626_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Season'),
        ),
    ]
