# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_playerranking_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamranking',
            old_name='weak',
            new_name='week',
        ),
    ]
