# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20170827_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='total_clearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='total_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='total_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_clearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_legs_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_legs_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamranking',
            name='total_matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
