# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170208_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchweek',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matchweek',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
