# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170627_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.League'),
        ),
    ]
