# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170627_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchweek',
            name='serial_id',
            field=models.IntegerField(default=0),
        ),
    ]
